api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/bundler"
  id = "paketo-buildpacks/bundler"
  name = "Paketo Bundler Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "f67a27c75fd262566e915b6e3005663cdd4a4ec5cf79e633bc39187f5f40f0bd"
    source = "http://github.com/bundler/bundler/tree/v1.17.3"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_1.17.3_linux_noarch_any-stack_f67a27c7.tgz"
    version = "1.17.3"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "43d1d64ed6022fd55fb6897286ec4558ca8b68265be291f5601b94c48e210cf1"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.19"
    source_sha256 = "3258301b85495f427949d8d825926d817392cca653f05479eaa7845f71c08aa0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.19_linux_noarch_any-stack_43d1d64e.tgz"
    version = "2.2.19"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "4e1d00c211f1805ef2ef8cea8d05a45a6280cb48f324fa439dcaa2d3c5069def"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.20"
    source_sha256 = "259ba486173d72a71df43fee8e3bc8dcb868c8a65e0c4020af3a6f13c3a57ff8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.20_linux_noarch_any-stack_4e1d00c2.tgz"
    version = "2.2.20"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
