api = "0.2"

[buildpack]
  id = "paketo-buildpacks/bundler"
  name = "Paketo Bundler Buildpack"
  homepage = "https://github.com/paketo-buildpacks/bundler"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "f67a27c75fd262566e915b6e3005663cdd4a4ec5cf79e633bc39187f5f40f0bd"
    source = "http://github.com/bundler/bundler/tree/v1.17.3"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_1.17.3_linux_noarch_any-stack_f67a27c7.tgz"
    version = "1.17.3"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "550c375027aa5478e34ac147a7633875757733dcb7b120a37978ec5add169dca"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.14"
    source_sha256 = "ae7a1756a3b51f2748e19cf4f51abe00e53f3091c0d824c9e39f6ac13be04336"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.14_linux_noarch_any-stack_550c3750.tgz"
    version = "2.2.14"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "ffadbc3c73a9ffeda8163b497a7b131fdd8a1edace204dce10637d087f1cede8"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.15"
    source_sha256 = "9295b52d6744076497b86a7dfe03ffa4599942f245558c98071b8a05e3535835"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.15_linux_noarch_any-stack_ffadbc3c.tgz"
    version = "2.2.15"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
