api = "0.2"

[buildpack]
  id = "paketo-buildpacks/bundler"
  name = "Paketo Bundler Buildpack"
  homepage = "https://github.com/paketo-buildpacks/bundler"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "f67a27c75fd262566e915b6e3005663cdd4a4ec5cf79e633bc39187f5f40f0bd"
    source = "http://github.com/bundler/bundler/tree/v1.17.3"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_1.17.3_linux_noarch_any-stack_f67a27c7.tgz"
    version = "1.17.3"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "f946e4078537877624ff8d9906be228f5c1aa4e0a3ccbc53d70f97fad3b7956f"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.5"
    source_sha256 = "1b8f19fb50cdc9d8b7e73cc460d814b6ec19602c1b3b0e16c00e5b41f0e8e5c1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.5_linux_noarch_any-stack_f946e407.tgz"
    version = "2.2.5"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "22a1fbb00268f30149fbc177e27dba56aa30024e583308b949202b5fa46d28ee"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.6"
    source_sha256 = "140ffb665029b029ce3afc1300c2c33aaaea1b6173e722279e021b28107e4893"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.6_linux_noarch_any-stack_22a1fbb0.tgz"
    version = "2.2.6"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
