api = "0.2"

[buildpack]
  id = "paketo-buildpacks/bundler"
  name = "Paketo Bundler Buildpack"
  homepage = "https://github.com/paketo-buildpacks/bundler"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "f67a27c75fd262566e915b6e3005663cdd4a4ec5cf79e633bc39187f5f40f0bd"
    source = "http://github.com/bundler/bundler/tree/v1.17.3"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_1.17.3_linux_noarch_any-stack_f67a27c7.tgz"
    version = "1.17.3"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "cc8eba812df00e5196a64b89b9df45508b2ae343af0726bd6bf705c5803e4734"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.0"
    source_sha256 = "65d7c3dc82651915d49a408769b6c5ccde8103b27a8b9be1c674899594613994"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.0_linux_noarch_any-stack_cc8eba81.tgz"
    version = "2.2.0"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "c13c7fa30508eec111db22033e3f9da3890efd87b8b850908cf7db62e0492d4a"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.2"
    source_sha256 = "aa266aaa692c18a9ea7f12da7a5584c94de26e016a6b72520fb48c0c6649621e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.2_linux_noarch_any-stack_c13c7fa3.tgz"
    version = "2.2.2"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
