api = "0.2"

[buildpack]
  id = "paketo-buildpacks/bundler"
  name = "Paketo Bundler Buildpack"
  homepage = "https://github.com/paketo-buildpacks/bundler"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "f67a27c75fd262566e915b6e3005663cdd4a4ec5cf79e633bc39187f5f40f0bd"
    source = "http://github.com/bundler/bundler/tree/v1.17.3"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_1.17.3_linux_noarch_any-stack_f67a27c7.tgz"
    version = "1.17.3"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "973357871484e3420c111c54530f0671e7fd3ca547407ecbee7f5d9c0e9e26ae"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.9"
    source_sha256 = "b7aa885d7c90c34552488b83fa1b8f3ee75a813395d3548840270c4f5ad46198"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.9_linux_noarch_any-stack_97335787.tgz"
    version = "2.2.9"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "2b65381f382a63b15597f8a3783a37441c5d8a599c9f4655a4f0235e489f043a"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.10"
    source_sha256 = "5fb16a2f6fad0bcd8fb593a592bfdde083a7901afb440ffac46a1983b09bad93"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.10_linux_noarch_any-stack_2b65381f.tgz"
    version = "2.2.10"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
