api = "0.2"

[buildpack]
  id = "paketo-buildpacks/bundler"
  name = "Paketo Bundler Buildpack"
  homepage = "https://github.com/paketo-buildpacks/bundler"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "f67a27c75fd262566e915b6e3005663cdd4a4ec5cf79e633bc39187f5f40f0bd"
    source = "http://github.com/bundler/bundler/tree/v1.17.3"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_1.17.3_linux_noarch_any-stack_f67a27c7.tgz"
    version = "1.17.3"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "9ed25e047f88ad71a374b4fb6fe863e5f9f3239bc194f57489b1fb97ac8c68a2"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.17"
    source_sha256 = "7acaaf4fad8761124d3b575e54c22040ebe596d4d47f3e5f57290615e4e26dd5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.17_linux_noarch_any-stack_9ed25e04.tgz"
    version = "2.2.17"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "559055a719dd33f9a144901de48a727f5a38ea1b2f9618ef890f1b52ca711386"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.18"
    source_sha256 = "79c4e66022f7a6fd2457103db0c88872e0ee1e1eb7a5fc975e22b0d33aa9a6d4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.18_linux_noarch_any-stack_559055a7.tgz"
    version = "2.2.18"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
