api = "0.2"

[buildpack]
  id = "paketo-buildpacks/bundler"
  name = "Paketo Bundler Buildpack"
  homepage = "https://github.com/paketo-buildpacks/bundler"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "f67a27c75fd262566e915b6e3005663cdd4a4ec5cf79e633bc39187f5f40f0bd"
    source = "http://github.com/bundler/bundler/tree/v1.17.3"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_1.17.3_linux_noarch_any-stack_f67a27c7.tgz"
    version = "1.17.3"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "cc8eba812df00e5196a64b89b9df45508b2ae343af0726bd6bf705c5803e4734"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.0"
    source_sha256 = "65d7c3dc82651915d49a408769b6c5ccde8103b27a8b9be1c674899594613994"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.0_linux_noarch_any-stack_cc8eba81.tgz"
    version = "2.2.0"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "8a6b1111853989f7adb52e31095281026b33b9aba6e867370735042fccb69f49"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.3"
    source_sha256 = "6acefda4aeb34cb3d69aff06affce10424d69f484402a9f7f5577e8c698070db"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.3_linux_noarch_any-stack_8a6b1111.tgz"
    version = "2.2.3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
