api = "0.2"

[buildpack]
  id = "paketo-community/bundler"
  name = "Bundler Buildpack"

[metadata]
  include_files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "f67a27c75fd262566e915b6e3005663cdd4a4ec5cf79e633bc39187f5f40f0bd"
    source = "http://github.com/bundler/bundler/tree/v1.17.3"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_1.17.3_linux_noarch_any-stack_f67a27c7.tgz"
    version = "1.17.3"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "d17dcc07a6fd5a0eb9361a1837d410226f2b81c2ceb75976e07f7859971c0ce3"
    source = "https://github.com/bundler/bundler/tree/v2.1.4"
    source_sha256 = "50014d21d6712079da4d6464de12bb93c278f87c9200d0b60ba99f32c25af489"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.1.4_linux_noarch_any-stack_d17dcc07.tgz"
    version = "2.1.4"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
