api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/bundler"
  id = "paketo-buildpacks/bundler"
  name = "Paketo Bundler Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "f67a27c75fd262566e915b6e3005663cdd4a4ec5cf79e633bc39187f5f40f0bd"
    source = "http://github.com/bundler/bundler/tree/v1.17.3"
    source_sha256 = "bc4bf75b548b27451aa9f443b18c46a739dd22ad79f7a5f90b485376a67dc352"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_1.17.3_linux_noarch_any-stack_f67a27c7.tgz"
    version = "1.17.3"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "b4bbd4ea7164f3faba385aafb7c5f1c7f76af0333541acb59e2df7b725a99561"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.21"
    source_sha256 = "3c8dc5e0cf66d385a9b33751e54986290d42023c5e1bba2b5df094917b6e234a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.21_linux_noarch_any-stack_b4bbd4ea.tgz"
    version = "2.2.21"

  [[metadata.dependencies]]
    id = "bundler"
    name = "Bundler"
    sha256 = "233b3d27f41b553406cc56bf459c3900f53b98fe8fab4ee6c7162e072b917069"
    source = "https://github.com/rubygems/rubygems/tree/v2.2.22"
    source_sha256 = "7e7a5490154b37eefa8940f50a33bae1e12657656a1b007c4144c80474fa86e2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler_2.2.22_linux_noarch_any-stack_233b3d27.tgz"
    version = "2.2.22"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
